// Customer App - Bookings API Helper
// Handles booking creation, fetching, subscriptions, and cancellation

import { supabase } from "./supabase";
import type { Booking, ReceiverDetails, SelectedVehicle } from "@/types/type";

// =====================================================
// BOOKING CREATION
// =====================================================

export interface CreateBookingParams {
  customerId: string;
  originAddress: string;
  originLatitude: number;
  originLongitude: number;
  destinationAddress: string;
  destinationLatitude: number;
  destinationLongitude: number;
  vehicle: SelectedVehicle;
  receiverDetails: ReceiverDetails;
  goodsDescription?: string;
  tipAmount?: number;
  fareMultiplier?: number;
}

interface CreateBookingAddonParam {
  code: string;
  quantity?: number;
}

export interface DriverLocationSnapshot {
  bookingId?: string | null;
  latitude: number;
  longitude: number;
  heading?: number;
  recordedAt?: string;
}

// Generate unique booking number with nanosecond precision and randomness
// Format: CARTR-{timestamp}-{nano}-{random} = ~30 characters
function generateBookingNumber(): string {
  const timestamp = Date.now().toString(36).toUpperCase();
  // Add sub-millisecond precision using performance.now()
  const nano = Math.floor((performance.now() % 1) * 1000000).toString(36).toUpperCase();
  // Add random component for extra uniqueness
  const random = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `CARTR-${timestamp}${nano}${random}`;
}

// Generate 4-digit OTP
function generateOTP(): string {
  // Use Math.random for React Native compatibility
  const otp = Math.floor(1000 + Math.random() * 9000);
  return otp.toString();
}

/**
 * Create a new booking in the database
 */
export async function createBooking(params: CreateBookingParams): Promise<{
  data: Booking | null;
  error: string | null;
}> {
  try {
    console.log('[createBooking] Function called');
    console.log('[createBooking] Params:', JSON.stringify(params, null, 2));
    
    const {
      customerId,
      vehicle,
      receiverDetails,
      goodsDescription,
      tipAmount = 0,
      fareMultiplier = 1.0,
    } = params;

    // Calculate driver payout
    const driverPayout = (vehicle.total_fare * fareMultiplier) + tipAmount;

    // Note: booking_number is auto-generated by database trigger
    const bookingData = {
      customer_id: customerId,
      origin_address: params.originAddress,
      origin_latitude: params.originLatitude,
      origin_longitude: params.originLongitude,
      destination_address: params.destinationAddress,
      destination_latitude: params.destinationLatitude,
      destination_longitude: params.destinationLongitude,
      vehicle_type: vehicle.vehicle_type,
      estimated_distance: vehicle.distance_km,
      estimated_duration: vehicle.duration_minutes,
      base_fare: vehicle.base_fare,
      distance_fare: vehicle.distance_fare,
      time_fare: vehicle.time_fare,
      surge_multiplier: vehicle.surge_multiplier,
      total_fare: vehicle.total_fare,
      tip_amount: tipAmount,
      fare_multiplier: fareMultiplier,
      driver_payout: driverPayout,
      pickup_otp: generateOTP(),
      // delivery_otp is auto-generated by database trigger
      receiver_name: receiverDetails.name,
      receiver_phone: receiverDetails.phone,
      goods_description: goodsDescription || null,
      status: 'pending',
      payment_status: 'pending',
      payment_method: 'cash', // Default to cash, can be changed later
      // Booking expires in 3 minutes if no driver accepts to cleanly align with UI timeout
      expires_at: new Date(Date.now() + 3 * 60 * 1000).toISOString(),
    };

    console.log('[createBooking] Data to insert (NO booking_number):', JSON.stringify(bookingData, null, 2));
    console.log('[createBooking] Inserting into database...');

    const { data, error } = await supabase
      .from('bookings')
      .insert(bookingData)
      .select()
      .single();

    if (error) {
      console.error('[createBooking] Database error:', error);
      return { data: null, error: error.message };
    }

    console.log('[createBooking] Success! Booking created:', data);
    return { data: data as Booking, error: null };
  } catch (err: any) {
    console.error('[createBooking] Exception:', err);
    return { data: null, error: err.message || 'Failed to create booking' };
  }
}

// =====================================================
// FETCH BOOKINGS
// =====================================================

/**
 * Get a single booking by ID with driver details
 */
export async function getBookingById(bookingId: string): Promise<{
  data: Booking | null;
  error: string | null;
}> {
  try {
    const { data, error } = await supabase
      .from('bookings')
      .select(`
        *,
        driver:drivers(
          id,
          user_id,
          vehicle_number,
          vehicle_model,
          vehicle_color,
          rating,
          current_latitude,
          current_longitude,
          last_location_update,
          user:users!drivers_user_id_fkey(id, name, phone, avatar_url)
        ),
        booking_addons(
          quantity,
          unit_price,
          total_price,
          addon_services(name, code, price)
        )
      `)
      .eq('id', bookingId)
      .single();

    if (error) {
      return { data: null, error: error.message };
    }

    if (
      data?.driver_id &&
      ['accepted', 'driver_arrived', 'in_progress', 'completed'].includes(data.status) &&
      !data.driver
    ) {
      console.warn('[getBookingById] Assigned booking is missing joined driver details. This usually points to RLS/policy issues on drivers/users.', {
        bookingId,
        status: data.status,
        driver_id: data.driver_id,
      });
    }

    return { data: data as Booking, error: null };
  } catch (err: any) {
    return { data: null, error: err.message };
  }
}

/**
 * Get all bookings for a customer (history)
 */
export async function getCustomerBookings(customerId: string): Promise<{
  data: Booking[];
  error: string | null;
}> {
  try {
    console.log('[GET_CUSTOMER_BOOKINGS] Fetching bookings for customer_id:', customerId);
    
    const { data, error } = await supabase
      .from('bookings')
      .select(`
        *,
        driver:drivers(
          id,
          user_id,
          vehicle_number,
          vehicle_model,
          vehicle_color,
          rating,
          user:users!drivers_user_id_fkey(id, name, phone, avatar_url)
        )
      `)
      .eq('customer_id', customerId)
      .order('created_at', { ascending: false });

    console.log('[GET_CUSTOMER_BOOKINGS] Query result:', {
      hasData: !!data,
      dataLength: data?.length || 0,
      error: error?.message || null,
      errorCode: error?.code || null,
      errorDetails: error?.details || null
    });

    if (data && data.length > 0) {
      console.log('[GET_CUSTOMER_BOOKINGS] Sample booking:', {
        id: data[0].id.slice(0, 8),
        status: data[0].status,
        customer_id: data[0].customer_id,
        driver_id: data[0].driver_id,
        created_at: data[0].created_at
      });
    }

    if (error) {
      console.error('[GET_CUSTOMER_BOOKINGS] Supabase error:', error);
      return { data: [], error: error.message };
    }

    return { data: data as Booking[], error: null };
  } catch (err: any) {
    console.error('[GET_CUSTOMER_BOOKINGS] Exception:', err);
    return { data: [], error: err.message };
  }
}

// =====================================================
// REAL-TIME SUBSCRIPTIONS
// =====================================================

/**
 * Subscribe to booking status updates (real-time)
 * Used when waiting for driver to accept
 */
export function subscribeToBooking(
  bookingId: string,
  onUpdate: (booking: Booking) => void
) {
  let lastStateString = '';

  const pollLatest = async () => {
    try {
      const { data } = await getBookingById(bookingId);
      if (data) {
        const stateString = JSON.stringify(data);
        if (stateString !== lastStateString) {
          lastStateString = stateString;
          onUpdate(data);
        }
      }
    } catch (e) {
      console.warn('[subscribeToBooking] Polling failed:', e);
    }
  };

  // Fallback polling every 3 seconds (reduced from 5s for faster detection)
  const pollInterval = setInterval(pollLatest, 3000);

  // Unique channel name to prevent Supabase Realtime collisions on re-mount
  const channelName = `customer-booking-${bookingId}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;

  const subscription = supabase
    .channel(channelName)
    .on(
      'postgres_changes',
      {
        event: 'UPDATE',
        schema: 'public',
        table: 'bookings',
        filter: `id=eq.${bookingId}`,
      },
      async (payload) => {
        const updatedBooking = payload.new as Booking;

        // Re-hydrate the booking so screens receive the latest relational data
        // together with the status change. This avoids stale UI state on track pages.
        const { data } = await getBookingById(bookingId);
        const bookingToUpdate = data ?? updatedBooking;
        
        lastStateString = JSON.stringify(bookingToUpdate);
        onUpdate(bookingToUpdate);
      }
    )
    .subscribe((status) => {
      console.log(`[subscribeToBooking] Channel ${channelName} status:`, status);
      // Immediately poll when connected to catch any updates missed during setup
      if (status === 'SUBSCRIBED') {
        void pollLatest();
      }
    });

  return () => {
    clearInterval(pollInterval);
    subscription.unsubscribe();
  };
}

/**
 * Subscribe to driver location updates (using history table for reliability)
 * This is better because driver_locations is already enabled for Realtime
 */
export function subscribeToBookingDriverLocation(
  bookingId: string,
  driverId: string,
  onLocationUpdate: (location: DriverLocationSnapshot) => void
) {
  const subscription = supabase
    .channel(`reli-driver-location-${bookingId}-${driverId}`)
    .on(
      'postgres_changes',
      {
        event: 'INSERT',
        schema: 'public',
        table: 'driver_locations',
        filter: `booking_id=eq.${bookingId}`,
      },
      (payload) => {
        console.log(`[REALTIME-LOCATION] New position for driver ${driverId}:`, payload.new);
        const { booking_id, latitude, longitude, heading, recorded_at } = payload.new;
        if (latitude != null && longitude != null) {
          onLocationUpdate({
            bookingId: booking_id ?? null,
            latitude: Number(latitude),
            longitude: Number(longitude),
            heading: heading != null ? Number(heading) : undefined,
            recordedAt: recorded_at ?? undefined,
          });
        }
      }
    )
    .subscribe((status) => {
      console.log(`[REALTIME-LOCATION] Subscription status for ${driverId}:`, status);
    });

  return () => {
    subscription.unsubscribe();
  };
}

export async function getLatestDriverLocation(
  bookingId: string,
  options?: {
    driverId?: string | null;
    notBefore?: string | null;
  }
): Promise<{ data: DriverLocationSnapshot | null; error: string | null }> {
  try {
    const notBeforeTimestamp = options?.notBefore ? new Date(options.notBefore).getTime() : 0;
    const { data: historyRow, error: historyError } = await supabase
      .from('driver_locations')
      .select('latitude, longitude, heading, recorded_at')
      .eq('booking_id', bookingId)
      .order('recorded_at', { ascending: false })
      .limit(1)
      .maybeSingle();

    if (historyError) {
      console.warn('[getLatestDriverLocation] History lookup failed, falling back to drivers table:', historyError.message);
    }

    if (historyRow?.latitude != null && historyRow?.longitude != null) {
      const recordedAtTimestamp = historyRow.recorded_at ? new Date(historyRow.recorded_at).getTime() : 0;
      if (notBeforeTimestamp && recordedAtTimestamp && recordedAtTimestamp < notBeforeTimestamp) {
        return { data: null, error: null };
      }

      return {
        data: {
          bookingId,
          latitude: Number(historyRow.latitude),
          longitude: Number(historyRow.longitude),
          heading: historyRow.heading != null ? Number(historyRow.heading) : undefined,
          recordedAt: historyRow.recorded_at ?? undefined,
        },
        error: null,
      };
    }

    if (!options?.driverId) {
      return { data: null, error: null };
    }

    const { data: driverRow, error: driverError } = await supabase
      .from('drivers')
      .select('current_latitude, current_longitude, last_location_update')
      .eq('id', options.driverId)
      .maybeSingle();

    if (driverError) {
      return { data: null, error: driverError.message };
    }

    if (driverRow?.current_latitude == null || driverRow?.current_longitude == null) {
      return { data: null, error: null };
    }

    const lastUpdateTimestamp = driverRow.last_location_update ? new Date(driverRow.last_location_update).getTime() : 0;
    if (notBeforeTimestamp && lastUpdateTimestamp && lastUpdateTimestamp < notBeforeTimestamp) {
      return { data: null, error: null };
    }

    return {
      data: {
        bookingId,
        latitude: Number(driverRow.current_latitude),
        longitude: Number(driverRow.current_longitude),
        recordedAt: driverRow.last_location_update ?? undefined,
      },
      error: null,
    };
  } catch (err: any) {
    return { data: null, error: err.message ?? 'Failed to fetch latest driver location' };
  }
}

/**
 * Subscribe to driver profile updates (legacy/fallback)
 */
export function subscribeToDriverLocation(
  driverId: string,
  onLocationUpdate: (location: { latitude: number; longitude: number; heading?: number; recordedAt?: string }) => void
) {
  const subscription = supabase
    .channel(`driver-profile-${driverId}`)
    .on(
      'postgres_changes',
      {
        event: 'UPDATE',
        schema: 'public',
        table: 'drivers',
        filter: `id=eq.${driverId}`,
      },
      (payload) => {
        const { current_latitude, current_longitude, current_heading } = payload.new;
        if (current_latitude != null && current_longitude != null) {
          onLocationUpdate({
            latitude: Number(current_latitude),
            longitude: Number(current_longitude),
            heading: current_heading != null ? Number(current_heading) : undefined,
            recordedAt: (payload.new as any).last_location_update ?? undefined,
          });
        }
      }
    )
    .subscribe();

  return () => {
    subscription.unsubscribe();
  };
}

// =====================================================
// BOOKING ACTIONS
// =====================================================

/**
 * Cancel a pending booking
 */
export async function cancelBooking(
  bookingId: string,
  userId: string,
  reason?: string
): Promise<{ success: boolean; error: string | null }> {
  try {
    const { data, error } = await supabase.rpc('cancel_booking_by_customer_v2' as any, {
      p_booking_id: bookingId,
      p_customer_user_id: userId,
      p_reason: reason || 'Cancelled by customer',
    });

    if (error) {
      return { success: false, error: error.message };
    }

    const result = data as any;
    if (!result?.success) {
      return { success: false, error: result?.error || 'Failed to cancel booking' };
    }

    return { success: true, error: null };
  } catch (err: any) {
    return { success: false, error: err.message };
  }
}

/**
 * Update booking with increased price (retry after timeout)
 * Works for pending bookings even when expires_at has passed - extends search window
 */
export async function retryBookingWithIncreasedPrice(
  bookingId: string,
  customerId: string,
  newTipAmount: number,
  newFareMultiplier: number
): Promise<{ success: boolean; error: string | null }> {
  try {
    const { data, error } = await supabase.rpc('retry_booking_with_tip_and_wallet_sync' as any, {
      p_booking_id: bookingId,
      p_customer_id: customerId,
      p_new_tip_amount: newTipAmount,
      p_new_fare_multiplier: newFareMultiplier,
    });

    if (error) {
      return { success: false, error: error.message };
    }

    const result = data as any;
    if (!result?.success) {
      return { success: false, error: result?.error || 'Failed to update booking' };
    }

    return { success: true, error: null };
  } catch (err: any) {
    return { success: false, error: err.message };
  }
}

/**
 * Create a new booking together with any selected add-ons in one DB-side flow.
 * This avoids a race where drivers see the booking before booking_addons exists.
 */
export async function createBookingWithAddons(
  params: CreateBookingParams,
  addons: CreateBookingAddonParam[] = []
): Promise<{
  data: Booking | null;
  error: string | null;
}> {
  try {
    const {
      customerId,
      vehicle,
      receiverDetails,
      goodsDescription,
      tipAmount = 0,
      fareMultiplier = 1.0,
    } = params;

    const driverPayout = (vehicle.total_fare * fareMultiplier) + tipAmount;
    const expiresAt = new Date(Date.now() + 3 * 60 * 1000).toISOString();

    const addonPayload = addons
      .filter((addon) => typeof addon.code === 'string' && addon.code.trim().length > 0)
      .map((addon) => ({
        code: addon.code.trim(),
        quantity: addon.quantity && addon.quantity > 0 ? addon.quantity : 1,
      }));

    const { data: createdBooking, error } = await supabase.rpc('create_booking_with_addons' as any, {
      p_customer_id: customerId,
      p_origin_address: params.originAddress,
      p_origin_latitude: params.originLatitude,
      p_origin_longitude: params.originLongitude,
      p_destination_address: params.destinationAddress,
      p_destination_latitude: params.destinationLatitude,
      p_destination_longitude: params.destinationLongitude,
      p_vehicle_type: vehicle.vehicle_type,
      p_estimated_distance: vehicle.distance_km,
      p_estimated_duration: vehicle.duration_minutes,
      p_base_fare: vehicle.base_fare,
      p_distance_fare: vehicle.distance_fare,
      p_time_fare: vehicle.time_fare,
      p_surge_multiplier: vehicle.surge_multiplier,
      p_total_fare: vehicle.total_fare,
      p_tip_amount: tipAmount,
      p_fare_multiplier: fareMultiplier,
      p_driver_payout: driverPayout,
      p_pickup_otp: generateOTP(),
      p_receiver_name: receiverDetails.name,
      p_receiver_phone: receiverDetails.phone,
      p_goods_description: goodsDescription || null,
      p_payment_status: 'pending',
      p_payment_method: 'cash',
      p_expires_at: expiresAt,
      p_addons: addonPayload,
    });

    if (error || !createdBooking?.id) {
      return { data: null, error: error?.message || 'Failed to create booking' };
    }

    const { data: hydratedBooking, error: fetchError } = await getBookingById(createdBooking.id);
    if (fetchError) {
      return {
        data: createdBooking as unknown as Booking,
        error: null,
      };
    }

    return { data: hydratedBooking, error: null };
  } catch (err: any) {
    console.error('[createBookingWithAddons] Exception:', err);
    return { data: null, error: err.message || 'Failed to create booking with add-ons' };
  }
}

export async function expireBookingSearch(
  bookingId: string,
  customerId: string
): Promise<{ success: boolean; error: string | null }> {
  try {
    const { data, error } = await supabase.rpc('expire_booking_search' as any, {
      p_booking_id: bookingId,
      p_customer_id: customerId,
    });

    if (error) {
      return { success: false, error: error.message };
    }

    const result = data as any;
    if (!result?.success) {
      return { success: false, error: result?.error || 'Failed to expire booking search' };
    }

    return { success: true, error: null };
  } catch (err: any) {
    return { success: false, error: err.message };
  }
}
