// Customer App - Bookings API Helper
// Handles booking creation, fetching, subscriptions, and cancellation

import { supabase } from "./supabase";
import type { Booking, ReceiverDetails, SelectedVehicle } from "@/types/type";

// =====================================================
// BOOKING CREATION
// =====================================================

export interface CreateBookingParams {
  customerId: string;
  originAddress: string;
  originLatitude: number;
  originLongitude: number;
  destinationAddress: string;
  destinationLatitude: number;
  destinationLongitude: number;
  vehicle: SelectedVehicle;
  receiverDetails: ReceiverDetails;
  goodsDescription?: string;
  tipAmount?: number;
  fareMultiplier?: number;
}

// Generate unique booking number with nanosecond precision and randomness
// Format: CARTR-{timestamp}-{nano}-{random} = ~30 characters
function generateBookingNumber(): string {
  const timestamp = Date.now().toString(36).toUpperCase();
  // Add sub-millisecond precision using performance.now()
  const nano = Math.floor((performance.now() % 1) * 1000000).toString(36).toUpperCase();
  // Add random component for extra uniqueness
  const random = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `CARTR-${timestamp}${nano}${random}`;
}

// Generate 4-digit OTP
function generateOTP(): string {
  return Math.floor(1000 + Math.random() * 9000).toString();
}

/**
 * Create a new booking in the database
 */
export async function createBooking(params: CreateBookingParams): Promise<{
  data: Booking | null;
  error: string | null;
}> {
  try {
    console.log('[createBooking] Function called');
    console.log('[createBooking] Params:', JSON.stringify(params, null, 2));
    
    const {
      customerId,
      vehicle,
      receiverDetails,
      goodsDescription,
      tipAmount = 0,
      fareMultiplier = 1.0,
    } = params;

    // Calculate driver payout
    const driverPayout = (vehicle.total_fare * fareMultiplier) + tipAmount;

    // Note: booking_number is auto-generated by database trigger
    const bookingData = {
      customer_id: customerId,
      origin_address: params.originAddress,
      origin_latitude: params.originLatitude,
      origin_longitude: params.originLongitude,
      destination_address: params.destinationAddress,
      destination_latitude: params.destinationLatitude,
      destination_longitude: params.destinationLongitude,
      vehicle_type: vehicle.vehicle_type,
      estimated_distance: vehicle.distance_km,
      estimated_duration: vehicle.duration_minutes,
      base_fare: vehicle.base_fare,
      distance_fare: vehicle.distance_fare,
      time_fare: vehicle.time_fare,
      surge_multiplier: vehicle.surge_multiplier,
      total_fare: vehicle.total_fare,
      tip_amount: tipAmount,
      fare_multiplier: fareMultiplier,
      driver_payout: driverPayout,
      pickup_otp: generateOTP(),
      // delivery_otp is auto-generated by database trigger
      receiver_name: receiverDetails.name,
      receiver_phone: receiverDetails.phone,
      goods_description: goodsDescription || null,
      status: 'pending',
      payment_status: 'pending',
      payment_method: 'cash', // Default to cash, can be changed later
      // Booking expires in 3 minutes if no driver accepts
      expires_at: new Date(Date.now() + 3 * 60 * 1000).toISOString(),
    };

    console.log('[createBooking] Data to insert (NO booking_number):', JSON.stringify(bookingData, null, 2));
    console.log('[createBooking] Inserting into database...');

    const { data, error } = await supabase
      .from('bookings')
      .insert(bookingData)
      .select()
      .single();

    if (error) {
      console.error('[createBooking] Database error:', error);
      return { data: null, error: error.message };
    }

    console.log('[createBooking] Success! Booking created:', data);
    return { data: data as Booking, error: null };
  } catch (err: any) {
    console.error('[createBooking] Exception:', err);
    return { data: null, error: err.message || 'Failed to create booking' };
  }
}

// =====================================================
// FETCH BOOKINGS
// =====================================================

/**
 * Get a single booking by ID with driver details
 */
export async function getBookingById(bookingId: string): Promise<{
  data: Booking | null;
  error: string | null;
}> {
  try {
    const { data, error } = await supabase
      .from('bookings')
      .select(`
        *,
        driver:drivers(
          id,
          vehicle_number,
          vehicle_model,
          vehicle_color,
          rating,
          current_latitude,
          current_longitude,
          user:users!drivers_user_id_fkey(name, phone, avatar_url)
        )
      `)
      .eq('id', bookingId)
      .single();

    if (error) {
      return { data: null, error: error.message };
    }

    return { data: data as Booking, error: null };
  } catch (err: any) {
    return { data: null, error: err.message };
  }
}

/**
 * Get all bookings for a customer (history)
 */
export async function getCustomerBookings(customerId: string): Promise<{
  data: Booking[];
  error: string | null;
}> {
  try {
    console.log('[GET_CUSTOMER_BOOKINGS] Fetching bookings for customer_id:', customerId);
    
    const { data, error } = await supabase
      .from('bookings')
      .select(`
        *,
        driver:drivers(
          id,
          vehicle_number,
          vehicle_model,
          vehicle_color,
          rating,
          user:users!drivers_user_id_fkey(name, phone, avatar_url)
        )
      `)
      .eq('customer_id', customerId)
      .order('created_at', { ascending: false });

    console.log('[GET_CUSTOMER_BOOKINGS] Query result:', {
      hasData: !!data,
      dataLength: data?.length || 0,
      error: error?.message || null,
      errorCode: error?.code || null,
      errorDetails: error?.details || null
    });

    if (data && data.length > 0) {
      console.log('[GET_CUSTOMER_BOOKINGS] Sample booking:', {
        id: data[0].id.slice(0, 8),
        status: data[0].status,
        customer_id: data[0].customer_id,
        driver_id: data[0].driver_id,
        created_at: data[0].created_at
      });
    }

    if (error) {
      console.error('[GET_CUSTOMER_BOOKINGS] Supabase error:', error);
      return { data: [], error: error.message };
    }

    return { data: data as Booking[], error: null };
  } catch (err: any) {
    console.error('[GET_CUSTOMER_BOOKINGS] Exception:', err);
    return { data: [], error: err.message };
  }
}

// =====================================================
// REAL-TIME SUBSCRIPTIONS
// =====================================================

/**
 * Subscribe to booking status updates (real-time)
 * Used when waiting for driver to accept
 */
export function subscribeToBooking(
  bookingId: string,
  onUpdate: (booking: Booking) => void
) {
  const subscription = supabase
    .channel(`customer-booking-${bookingId}`)
    .on(
      'postgres_changes',
      {
        event: 'UPDATE',
        schema: 'public',
        table: 'bookings',
        filter: `id=eq.${bookingId}`,
      },
      (payload) => {
        onUpdate(payload.new as Booking);
      }
    )
    .subscribe();

  return () => {
    subscription.unsubscribe();
  };
}

/**
 * Subscribe to driver location updates
 * Used during trip tracking
 */
export function subscribeToDriverLocation(
  driverId: string,
  onLocationUpdate: (location: { latitude: number; longitude: number; heading?: number }) => void
) {
  const subscription = supabase
    .channel(`driver-location-${driverId}`)
    .on(
      'postgres_changes',
      {
        event: 'UPDATE',
        schema: 'public',
        table: 'drivers',
        filter: `id=eq.${driverId}`,
      },
      (payload) => {
        const { current_latitude, current_longitude } = payload.new;
        if (current_latitude && current_longitude) {
          onLocationUpdate({
            latitude: parseFloat(current_latitude),
            longitude: parseFloat(current_longitude),
          });
        }
      }
    )
    .subscribe();

  return () => {
    subscription.unsubscribe();
  };
}

// =====================================================
// BOOKING ACTIONS
// =====================================================

/**
 * Cancel a pending booking
 */
export async function cancelBooking(
  bookingId: string,
  userId: string,
  reason?: string
): Promise<{ success: boolean; error: string | null }> {
  try {
    const { error } = await supabase
      .from('bookings')
      .update({
        status: 'cancelled',
        cancelled_at: new Date().toISOString(),
        cancelled_by: userId,
        cancellation_reason: reason || 'Cancelled by customer',
        updated_at: new Date().toISOString(),
      })
      .eq('id', bookingId)
      .in('status', ['pending', 'accepted']); // Can only cancel if pending or accepted

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, error: null };
  } catch (err: any) {
    return { success: false, error: err.message };
  }
}

/**
 * Update booking with increased price (retry after timeout)
 */
export async function retryBookingWithIncreasedPrice(
  bookingId: string,
  newTipAmount: number,
  newFareMultiplier: number
): Promise<{ success: boolean; error: string | null }> {
  try {
    // First get the current booking to calculate new payout
    const { data: booking, error: fetchError } = await supabase
      .from('bookings')
      .select('total_fare')
      .eq('id', bookingId)
      .single();

    if (fetchError || !booking) {
      return { success: false, error: 'Booking not found' };
    }

    const newDriverPayout = (booking.total_fare * newFareMultiplier) + newTipAmount;

    const { error } = await supabase
      .from('bookings')
      .update({
        tip_amount: newTipAmount,
        fare_multiplier: newFareMultiplier,
        driver_payout: newDriverPayout,
        status: 'pending', // Reset to pending
        // Extend expiration by 3 more minutes
        expires_at: new Date(Date.now() + 3 * 60 * 1000).toISOString(),
        updated_at: new Date().toISOString(),
      })
      .eq('id', bookingId)
      .in('status', ['pending']); // Only update if still pending

    if (error) {
      return { success: false, error: error.message };
    }

    return { success: true, error: null };
  } catch (err: any) {
    return { success: false, error: err.message };
  }
}
